services:

  script:
    image: ingestion:1
    # set attribute to manage credentials
    depends_on:
      - db
    env_file:
      - staging/credentials/.env
    environment:
      ENV: staging/credentials/
      KEY_FILE: /run/secrets/api_secret
      LOG_FILE: /logs/
      PASS_FILE: /run/secrets/postgres_pass
      SQL_FILE: /src/sql
      USER_FILE: /run/secrets/postgres_user
    volumes:
      - ingestionlog:/logs/
      - ./dockerlogs/:/logs/
    secrets:
      - api_secret
      - postgres_user
      - postgres_pass

  db:
    image: postgres:17
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_pass
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    secrets:
      - postgres_user
      - postgres_pass

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080    

secrets:
  api_secret:
    file: ./staging/credentials/api_key.txt
  postgres_user:
    file: ./staging/credentials/db_user.txt
  postgres_pass:
    file: ./staging/credentials/db_pass.txt
volumes:
  ingestionlog:
  postgresdata:
  